name: Cypress tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1-5" # run every weekdays 5am

jobs:
  cypress_run_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install the dependencies...
        run: npm install
      - name: Setup environment variables...
        env:
          BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
          USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        run: |
        echo "This is my base url ${{ BASE_URL }}"
        echo "This is my username ${{ USERNAME }}"
        echo "This is my password ${{ PASSWORD }}"
      - name: Run cypress test ci...
        uses: cypress-io/github-action@v5
        with:
          start: npm run cypress:run:ci
