name: Cypress tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5' # run every weekdays 5am

jobs:
  cypress_run_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master # checkout code only from the 'master' branch
      - name: Install the dependencies...
        run: npm install
      - name: Run cypress test...
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run cypress:run:ci
