name: Cypress tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1-5" # run every weekdays 5am

jobs:
  cypress_run_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install the dependencies...
        run: npm install
      - name: Run cypress test...
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
        echo "This is my base url: $BASE_URL"
        echo "This is my username: $USERNAME"
        echo "This is my password: $PASSWORD"
        npm run cypress:run:ci

