name: Cypress tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1-5" # run every weekdays 5am

jobs:
  cypress_run_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install the dependencies...
        run: npm install
      - name: Setup environment variables...
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: echo "This is my base url ${{ vars.BASE_URL }}"
      - name: Run cypress test ci...
        run: npm run cypress:run:ci
